config/routes.rb
Amw2::Application.routes.draw do
 

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  
  root :to => 'static_pages#home'
  %w[home quote offsite_media_storage data_protection document_management online_backup_and_recovery 
    courier record_storage secure_shredding knowledge_base faq about contact].each do |page|
   get page, controller: "static_pages", action: page
   end
  
  resources :assets do
     collection { post :import }
   end
   

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/models/asset.rb
class Asset < ActiveRecord::Base
  attr_accessible :C3, :C4, :Client, :Date_In, :Day_One, :Description, :Media_Code, :Return_Date
  
  def self.import(file)
     spreadsheet = open_spreadsheet(file)
     header = spreadsheet.row(1)
     (2..spreadsheet.last_row).each do |i|
       row = Hash[[header, spreadsheet.row(i)].transpose]
       asset = find_by_id(row["id"]) || new
       asset.attributes = row.to_hash.slice(*accessible_attributes)
       asset.save!
     end
   end

   def self.open_spreadsheet(file)
     case File.extname(file.original_filename)
     when ".csv" then Roo::Csv.new(file.path)
     when ".xls" then Roo::Excel.new(file.path)
     when ".xlsx" then Roo::Excelx.new(file.path)
     else raise "Unknown file type: #{file.original_filename}"
     end
   end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/assets_controller.rb
class AssetsController < ApplicationController
  # GET /assets
  # GET /assets.json
  def index
    @assets = Asset.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @assets }
    end
  end
  
  def import
    Asset.import(params[:file])
    redirect_to root_url, notice: "Assets Imported"
  end

  # GET /assets/1
  # GET /assets/1.json
  def show
    @asset = Asset.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @asset }
    end
  end

  # GET /assets/new
  # GET /assets/new.json
  def new
    @asset = Asset.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @asset }
    end
  end

  # GET /assets/1/edit
  def edit
    @asset = Asset.find(params[:id])
  end

  # POST /assets
  # POST /assets.json
  def create
    @asset = Asset.new(params[:asset])

    respond_to do |format|
      if @asset.save
        format.html { redirect_to @asset, notice: 'Asset was successfully created.' }
        format.json { render json: @asset, status: :created, location: @asset }
      else
        format.html { render action: "new" }
        format.json { render json: @asset.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /assets/1
  # PUT /assets/1.json
  def update
    @asset = Asset.find(params[:id])

    respond_to do |format|
      if @asset.update_attributes(params[:asset])
        format.html { redirect_to @asset, notice: 'Asset was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @asset.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /assets/1
  # DELETE /assets/1.json
  def destroy
    @asset = Asset.find(params[:id])
    @asset.destroy

    respond_to do |format|
      format.html { redirect_to assets_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  def home
  end

  def quote
  end

  def offsite_media_storage
  end

  def data_protection
  end

  def document_management
  end

  def online_backup_and_recovery
  end

  def courier
  end

  def record_storage
  end

  def secure_shredding
  end

  def knowledge_base
  end

  def faq
  end

  def about
  end

  def contact
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/assets_helper.rb
module AssetsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
  def cloudFrontPath
    
    #"http://d2tdlvck5na3c0.cloudfront.net/clients/archivesmountain/"
    "http://mdlclients.s3.amazonaws.com/clients/archivesmountain/"
    
  end
  
end

app/views/assets/_form.html.erb
<%= form_for(@asset) do |f| %>
  <% if @asset.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@asset.errors.count, "error") %> prohibited this asset from being saved:</h2>

      <ul>
      <% @asset.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :Client %><br />
    <%= f.text_field :Client %>
  </div>
  <div class="field">
    <%= f.label :Description %><br />
    <%= f.text_field :Description %>
  </div>
  <div class="field">
    <%= f.label :C3 %><br />
    <%= f.text_field :C3 %>
  </div>
  <div class="field">
    <%= f.label :C4 %><br />
    <%= f.text_field :C4 %>
  </div>
  <div class="field">
    <%= f.label :Media_Code %><br />
    <%= f.text_field :Media_Code %>
  </div>
  <div class="field">
    <%= f.label :Date_In %><br />
    <%= f.date_select :Date_In %>
  </div>
  <div class="field">
    <%= f.label :Day_One %><br />
    <%= f.date_select :Day_One %>
  </div>
  <div class="field">
    <%= f.label :Return_Date %><br />
    <%= f.date_select :Return_Date %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/assets/edit.html.erb
<h1>Editing asset</h1>

<%= render 'form' %>

<%= link_to 'Show', @asset %> |
<%= link_to 'Back', assets_path %>

app/views/assets/index.html.erb
<h1>Listing assets</h1>

<table id="assets">
<thead>  
  <tr>
    <th>Client</th>
    <th>Description</th>
    <th>C3</th>
    <th>C4</th>
    <th>Media code</th>
    <th>Date in</th>
    <th>Day one</th>
    <th>Return date</th>

  </tr>
</thead>
<tbody>
<% @assets.each do |asset| %>
  <tr>
    <td><%= asset.Client %></td>
    <td><%= asset.Description %></td>
    <td><%= asset.C3 %></td>
    <td><%= asset.C4 %></td>
    <td><%= asset.Media_Code %></td>
    <td><%= asset.Date_In %></td>
    <td><%= asset.Day_One %></td>
    <td><%= asset.Return_Date %></td>
  </tr>
<% end %>
</tbody>
</table>

<br />

<%= link_to 'New Asset', new_asset_path %>
<h2>Import Assets</h2>

<%= form_tag import_assets_path, multipart: true do %>
  <%= file_field_tag :file %>
  <%= submit_tag "Import" %>
<% end %>

app/views/assets/new.html.erb
<h1>New asset</h1>

<%= render 'form' %>

<%= link_to 'Back', assets_path %>

app/views/assets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Client:</b>
  <%= @asset.Client %>
</p>

<p>
  <b>Description:</b>
  <%= @asset.Description %>
</p>

<p>
  <b>C3:</b>
  <%= @asset.C3 %>
</p>

<p>
  <b>C4:</b>
  <%= @asset.C4 %>
</p>

<p>
  <b>Media code:</b>
  <%= @asset.Media_Code %>
</p>

<p>
  <b>Date in:</b>
  <%= @asset.Date_In %>
</p>

<p>
  <b>Day one:</b>
  <%= @asset.Day_One %>
</p>

<p>
  <b>Return date:</b>
  <%= @asset.Return_Date %>
</p>


<%= link_to 'Edit', edit_asset_path(@asset) %> |
<%= link_to 'Back', assets_path %>

app/views/layouts/_footer.html.erb
<section >
	<div class="panel">
<div class="row">
 <div class="small-5 columns"  >
	
		<h2>Our Information</h2>
		<ul class="contact">
			<li class="address">
				Archives Mountain<br />
				64 Barnabas Road Newtown,<br />
				CT 06470
			</li>
			<li class="email">
				<a href="mailto:info@ArchivesMountain.com">info@ArchivesMountain.com</a>
			</li>
			<li class="phone">
				Phone (203) 364-9272
			</li>
			<li class="phone">
				Toll Free (866) 996-9111
			</li>
			<li>
				Fax: (203) 714-7224
			</li>
		</ul>
	
      </div>
	  
      <div class="small-4  columns">
       
		<section>
			<h2>Our Services</h2>
			<ul class="style2">
				  <li><%= link_to_unless_current "Request a Quote", 'quote' %></li>
				
				<li class=""><%= link_to_unless_current "Offsite Media Storage", 'offsite_media_storage'  %> </li>
				<li class=""><%= link_to_unless_current "Data Protection & Recovery", 'data_protection'   %> </li>
				<li class=""><%= link_to_unless_current "Document Management", 'document_management' %> </li>
				<li class=""><%= link_to_unless_current "Online Backup & Recovery", 'online_backup_and_recovery'  %> </li>
				<li class=""><%= link_to_unless_current "Courier Service", 'courier'  %> </li>
				<li class=""><%= link_to_unless_current "Record Storage & Retrieval", 'record_storage'  %> </li>
				<li class=""><%= link_to_unless_current "Secure Document Shredding", 'secure_shredding' %> </li>
			
				
				
				
				
			</ul>
		</section>
	
      </div>
	  
      <div class="small-3  columns">
		
		<section>
			<h2>Links</h2>
			<ul class="style2">
				<li><%= link_to "Home", '/' %>
				<li class=""><%= link_to_unless_current "Knowledge Base", 'knowledge_base'  %> </li>
				<li class=""><%= link_to_unless_current "FAQs", 'faq'  %> </li>
		      
		        <li><%= link_to_unless_current "Contact us", 'contact' %></li>
				 <li><%= link_to_unless_current "About us", 'about' %></li>
		        <li><%= link_to_unless_current "Admin", 'admin'%></li>
		
			</ul>
		</section>
      </div>
	</div>
	  </div>
  </section>
   

					<div class="row">
						<div id="copyright">
							Copyright &copy; 2014 Archives Mountain All rights reserved.
						</div>
					</div>
				</footer>
			</div>

<!-- JQUERY -->

<!-- <script src="//ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>
<script src="http://code.jquery.com/ui/1.10.3/jquery-ui.js"></script>
<script src="js/script.js"></script> -->

<!-- Start of StatCounter Code 
<script type="text/javascript">
	var sc_project=6211741; 
	var sc_invisible=0; 
	var sc_security="4ba4a7a3"; 
	</script><script type="text/javascript"
	src="http://www.statcounter.com/counter/counter.js"></script><noscript><div
	class="statcounter"><a title="tumblr hit counter"
	href="http://statcounter.com/tumblr/" target="_blank"><img
	class="statcounter"
	src="http://c.statcounter.com/6211741/0/4ba4a7a3/0/"
	alt="tumblr hit counter" ></a></div></noscript>
 End of StatCounter Code -->

	</body>
</html>

app/views/layouts/_header.html.erb
<nav class="top-bar">
  <ul class="title-area">
    <li class="name">
      <h1>Toll Free (866) 996-9111</h1>
    </li>
  </ul>
  <section class="top-bar-section">
    <ul class="right">
      <li class="divider"></li>
      <li class="has-dropdown not-click"><%= link_to "Services", "/" %> 
	        <ul class="dropdown"><li class="title back js-generated"><h5><a href="#">Back</a></h5></li>
       		 	<li class=""><label>Archives Mountain Services</label></li>
				<li class=""><%= link_to_unless_current "Offsite Media Storage", 'offsite_media_storage'  %> </li>
				<li class=""><%= link_to_unless_current "Data Protection & Recovery", 'data_protection'   %> </li>
				<li class=""><%= link_to_unless_current "Document Management", 'document_management' %> </li>
				<li class=""><%= link_to_unless_current "Online Backup & Recovery", 'online_backup_and_recovery'  %> </li>
				<li class=""><%= link_to_unless_current "Courier Service", 'courier'  %> </li>
				<li class=""><%= link_to_unless_current "Record Storage & Retrieval", 'record_storage'  %> </li>
				<li class=""><%= link_to_unless_current "Secure Document Shredding", 'secure_shredding' %> </li>
				<li class="divider"></li>
				<li class=""><%= link_to_unless_current "Knowledge Base", 'knowledge_base'  %> </li>
				<li class=""><%= link_to_unless_current "FAQs", 'faq'  %> </li>
			</ul>
		</li>
      <li class="divider"></li>
      <li><%= link_to "Request a Quote", 'quote' %></li>
      <li class="divider"></li>
      <li><%= link_to "About us", 'about' %></li>
      <li class="divider"></li>
      <li><%= link_to "Contact us", 'contact' %></li>
      <li class="divider"></li>
      <li><%= link_to "Admin", 'admin'%></li>
    </ul>
  </section>
</nav>
<!-- ><a href="home"><img src="http://d2tdlvck5na3c0.cloudfront.net/clients/archivesmountain/images/logo.png" alt="Archives mountain logo"></a>
<a href="home"><img src= <%=cloudFrontPath%>images/logo.png alt="Archives mountain logo"></a> -->
 <section >

	 <div class="small-7 columns" >
	      	 <a href="home"><%= image_tag cloudFrontPath+"images/logo.png"%></a>
	      </div>
		  
	      <div class="small-3 columns">
	       
			<h4 class="subheader">
			<a href="https://maps.google.com/maps?q=64+Barnabas+Road+Newtown,+CT+06470&hnear=64+Barnabas+Rd,+Newtown,+Connecticut+06470&gl=us&t=h&z=16">
				64 Barnabas Road<br />Newtown, CT 06470
			</a>
			<br /></h4>
			
		
	      </div>
		  
	      <div class="small-2 columns">
			
			<a href="mailto:info@ArchivesMountain.com">info@ArchivesMountain.com</a><br />
			203.364.9272<br />
			866.996.9111<br />
			Fax: 203.714.7224<br />
	      </div>
		  <div class="row"></div>
	  </section>
	   


		  

app/views/layouts/application.html.erb
<!DOCTYPE html>
<!-- paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ -->
<!--[if lt IE 7 ]> <html class="ie6" lang="en"> <![endif]-->
<!--[if IE 7 ]>    <html class="ie7" lang="en"> <![endif]-->
<!--[if IE 8 ]>    <html class="ie8" lang="en"> <![endif]-->
<!--[if IE 9 ]>    <html class="ie9" lang="en"> <![endif]-->
<!--[if (gt IE 9)|!(IE)]><!--> <html lang="en"> <!--<![endif]-->
  <head>
  	<meta charset="utf-8" />
  	<!-- Uncomment to make IE8 render like IE7 -->
  	<!-- <meta http-equiv="X-UA-Compatible" content="IE=7" /> -->

  	<!-- Set the viewport width to device width for mobile -->
  	<meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= yield(:service) %> | <%= yield(:title) %></title>

  	<%= stylesheet_link_tag    "application" %>
  	<%= javascript_include_tag "vendor/custom.modernizr" %>
    <%= csrf_meta_tags %>


  </head>

  <body>
	  
	  
	  
	
      <% flash.each do |name, msg| %>
        <%= content_tag :div, msg, id: "flash_#{name}" %>
      <% end %>
	 
		
       
	  <%= render "layouts/header" %>
	  <%=yield %>
	  <%= render "layouts/footer" %>

    
    <%= javascript_include_tag "application" %>
  </body>
</html>

app/views/static_pages/about.html.erb
<% provide(:title, 'Archives Mountain') %>
<% provide(:service, 'About Us') %>

<!-- HEADER FILE -->
<?php include('inc/header '); ?>

		<!-- Search Wrapper -->
			<?php include('inc/search-wrapper ') ?>
				
		<!-- Main -->
			<div id="main-wrapper">
				<div class="5grid-layout">
					<div class="row">
						<div class="8u mobileUI-main-content">
							
							<!-- Content -->
								<div id="content">
								
									<!-- Article -->
										<article class="featured">
											<header>
												<h2>About us</h2>
											</header>
											<div>
												<img src="images/aboutus.jpg" style="max-width: 100%" alt="About Us">
											</div>
											<p>
												Archives Mountain is a full service off-site records and media storage management 
												company founded in 2000 and headquartered in western Connecticut. The company was 
												founded by several Information Technology executives who understand the daily problems 
												and challenges that our clients face every day to insure the protection of your most i
												mportant asset - information. We started the business knowing that success would only 
												come by providing a personalized approach coupled with a passion for exceptional customer 
												service … and a service level that is consistent, reliable and unmatched in the industry. 
												And we have succeeded!
											</p>
											<p>
												We are aligned with partner companies in the fields of Document Shredding, 
												Data Backup and Recovery and Business Continuity and Disaster Recovery in 
												order to provide a single source to our customers. The following are our primary service offerings
											</p>
											
											<ul style="list-style: circle">
												<li><span>OFF-SITE MEDIA STORAGE</span> and tape rotation management outsourcing to include daily courier service, 
												24/7/365 support, and guaranteed three (3) hour response time.</li>

												<li><span>PREMIUM RECORD STORAGE MANAGEMENT</span> in a secure storage depository 
												that contains the latest innovations in Security, Environmental 
												and Atmospheric Controls, and convenience for our customers. 
												Our fire protection system is the leader in the industry)</li>

												<li><span>INTERNET BASED FILE BACKUP AND RECOVERY</span> outsourcing 
												for companies and small businesses. Archives Mountain 
												is a value added reseller for Remote Data Backups 
												software which is a leader in the Internet data protection 
												market. Archives Mountain can provide daily monitoring of 
												corporate desktops and server backups without corporate 
												technology and at a cost that is a fraction of what other services cost.</li>
											</ul>
											<hr>
											<h2>Management Team</h2>
											<img src="images/peter.jpg" style="float: left; padding: 15px">
											<h3>Peter Farrell - President</h3>
											<p>
												Peter has more than fifteen years experience in providing systems 
												and services to Fortune 100 companies like General Foods, ABB, GE 
												Capital, American Can and others. He has held senior positions in 
												the roles of senior Technology Manager as well as Financial and Operations managerial responsibilities.

												In 2000, Mr. Farrell started the company with three other business 
												executives who also have Technology and Operations backgrounds 
												and extensive experience in customer support, business development 
												and Operational experience in small business development.

												During the last ten years, the Company has grown because 
												of our commitment to create a personalized service model with 
												our clients and customers that provide a value added benefit to both.

												Mr. Farrell has a BA from Iona College, New Rochelle, 
												NY and a MBA from the University of Utah.
											</p>
										</article>
							
								</div>

						</div>
						<div class="4u">
							<div class="right-sidebar">

								<!-- Sidebar -->
								<?php include('inc/right-side1 '); ?>
							
							</div>
						</div>
					</div>
				</div>
			</div>

			<!-- FOOTER FILE -->
		<?php include('inc/footer '); ?>

app/views/static_pages/contact.html.erb
<% provide(:title, 'Archives Mountain') %>
<% provide(:service, 'Contact Us') %>

<!-- FOR PHP SCRIPT -->
	
<!-- END OF PHP SCRIPT -->


<!-- HEADER FILE -->
<?php include('inc/header '); ?>

		<!-- Search Wrapper -->
			<?php include('inc/search-wrapper ') ?>
				
		<!-- Main -->
			<div id="main-wrapper">
				<div class="5grid-layout">
					<div class="row">
						<div class="8u mobileUI-main-content">
							
							<!-- Content -->
								<div id="content">
								
									<!-- Article -->
										<article class="featured">
											<header>
												<h2>Contact us</h2>
											</header>
											<img src="images/facility2.jpg" alt="facility" style="float:left; padding-right: 15px;">
											<p>Postal Address<br>PO Box 211<br>Hawleyville, CT 06440<br>
												<a href="http://www.mapquest.com/maps?address=64+Barnabas+Rd&city=Newtown&state=CT&zipcode=06470&redirect=true" target="_blank">Click here for driving directions</a></p>
											<br>	
											<hr>

											<p class="important">
												If you need immediate assistance, please call Archives Mountain at 866-996-9111 and notify operator that it is an EMERGENCY for customer service support.
											</p>
											<br>
											<p>Items in <span class="important">red</span> are required fields.</p>

											<div class="form-container">
												<div class="postResult">
													
													

												</div>
											<form  action="contact " method="post" id="POSTFORM"> 
												<table>
													<tr>
														<td><span class="important">First Name:</span><input type="text" name="fname"></td>
														<td><span class="important">Last Name:</span><input type="text" name="lname"></td>
													</tr>
													<tr>
														<td><span class="important">Email:</span><input type="text" name="email"></td>
														<td><span>Phone</span><input type="text" name="Phone"></td>
													</tr>
													<tr>
														<td><span>Comany Name:</span><input type="text" name="cname"></td>
													</tr>
													<tr>
														<td><span>Address 1:</span><input type="text" name="adress1"></td>
														<td><span>Address 2:</span><input type="text" name="address2"></td>
													</tr>
													<tr>
														<td><span>City:</span><input type="text" name="city"></td>
														<td><span>Sate/Province</span><input type="text" name="state"></td>
													</tr>
													<tr>
														<td><span>Zip/Postal Code:</span><input type="text" name="zip"></td>
													</tr>
													<tr>
														<td>
															<span>Reason For Contacting:</span>
															<select name="reason">
																<option>Please Select One</option>
																<option value="question/comment">Question/Comment</option>
																<option value="disaster recovery planning">Disaster Recovery Planning</option>
																<option value="Remote Data Backup">Remote Data Backup</option>
																<option value="Other">Other</option>
															</select>
														</td>
													</tr>
													<tr>
														<td>
															<span class="important" style="float: left">Question/Comment:</span>
															<textarea name="comments">
															</textarea>
														</td>
													</tr>
													<tr>
														<td>
															<span>Archives Mountain may contact me via e-mail:</span><br>
															<label>Yes</label><input type="radio" name="radio" value="yes">
															<label>No</label><input type="radio" name="radio" value="no">
														</td>
													</tr>
													<tr>
														<input type='hidden' name='submit' />
														<td>
															<input type="submit" value="Submit">
														</td>
													</tr>
												</table>
												
											</form>

											</div>
											
										</article>
							
								</div>

						</div>
						<div class="4u">
							<div class="right-sidebar">

								<!-- Sidebar -->
								<?php include('inc/right-side1 '); ?>
							
							</div>
						</div>
					</div>
				</div>
			</div>

			<!-- FOOTER FILE -->
		<?php include('inc/footer '); ?>

app/views/static_pages/courier.html.erb
<% provide(:title, 'Archives Mountain') %>
<% provide(:service, 'Courier Service') %>

<!-- HEADER FILE -->
<?php include('inc/header '); ?>

		<!-- Search Wrapper -->
			<?php include('inc/search-wrapper ') ?>
				
		<!-- Main -->
			<div id="main-wrapper">
				<div class="5grid-layout">
					<div class="row">
						<div class="8u mobileUI-main-content">
							
							<!-- Content -->
								<div id="content">
								
									<!-- Article -->
										<article class="featured">
											<header>
												<h2>Courier Service</h2>
											</header>
											<p>Courier service by Archives Mountain assures that your media is always safe and secure. We customize our pickup, delivery and schedules 
												around YOUR backup schedules and business requirements. Our courier service provides daily, 
												weekly and on demand courteous service and we guarantee that the courier will be at your location within the time window that you specify.
											</p>
											<div style="overflow: hidden">
												<img src="images/courier_van.jpg" alt="courier van" style="float: left; padding-right: 10px">
												<p style="width: 50%; margin: 10% auto;">Your media is transported in our secured vehicles to and from our vault.</p>
											</div>
										</article>
								
									<!-- Section 1 -->
										<section>
											<header>
												<h2 style="text-align: center">Business Benefits</h2>
											</header>
											<div class="5grid grid-spaced">
												<div class="row">
													<p>Everything about our offsite storage program and our courier service is built 
														for your convenience and to minimize your business risk. Customer satisfaction is our number one priority.
													</p>
													<p>
														Compare the individualized service that we provide vs. our competition: For starters, you will receive dependable,
														courteous service - each and every day. There are no surprises...AND... NO EXCUSES. You will even be given the 
														cell phone number of the driver. If there is bad weather or an accident you will be called and notified of 
														the expected arrival time. And…if you call for an emergency media return, <b>we will be at your location within 
														three hours - GUARANTEED… 365 days a year/24 hours a day</b>. And…we will call you when the courier is leaving
														and while in route so that you are always kept advised of their location and expected arrival time.
														You even have 24/7/365 phone contact with the owner of Archives Mountain.
													</p>
												</div>
												<div class="row" style="text-align: center">
													<h2>We are never satisfied until YOU are!</a></h2>
												</div>
											</div>
										</section>
								
								</div>

						</div>
						<div class="4u">
							<div class="right-sidebar">

								<!-- Sidebar -->
								<?php include('inc/right-side1 '); ?>
							
							</div>
						</div>
					</div>
				</div>
			</div>

			<!-- FOOTER FILE -->
		<?php include('inc/footer '); ?>

app/views/static_pages/data_protection.html.erb
<% provide(:title, 'Archives Mountain') %>
<% provide(:service, 'Data Protection & Recovery') %>

<!-- HEADER FILE -->
<?php include('inc/header '); ?>

		<!-- Search Wrapper -->
			<?php include('inc/search-wrapper ') ?>
				
		<!-- Main -->
			<div id="main-wrapper">
				<div class="5grid-layout">
					<div class="row">
						<div class="8u mobileUI-main-content">
							
							<!-- Content -->
								<div id="content">
								
									<!-- Article -->
										<article class="featured">
											<header>
												<h2>Data Protection & Recovery</h2>
												<hr>
											</header>
											<p>Archives Mountain helps organizations securely manage the increasing volume and complexity of data, 
											regardless of format. Our services enable you to store, access and manage information for recovery, compliance and legal discovery.</p>
											<p>We offer offsite backup programs for tape/disk media and document storage and record management as well as online backup and archiving solutions for 
												the data center and SMB businesses. We also provide services through our Partners for data restoration, data destruction, and Disaster Recovery 
												and Business Continuity at secure offsite locations.</p>
											<p>From Offsite Tape Vaulting, to Online Backup, to Disaster Recovery and Data Restoration, organizations of every size and sector have 
												trusted Archives Mountain for data protection and recovery services for over ten (10) years. And the reason is simple:</p>
											<h2>When you think about Media protection of your Corporate assets remember to keep these points in mind.</h2>
											<br>
											<ul class="circle">
												<li><h4>Archives Mountain is not the biggest in the business. That’s why we always try harder! We’re not satisfied until you are, because we know that you have a choice.</h4></li>
												<li><h4>We provide reliable, consistent, cost effective protection and the most personal and individual customer service in the business!</h4></li>
												<li><h4>The company was founded over ten years ago by several Information Technology executives who understand the daily problems and challenges that our clients face every day to insure the protection of your most important asset - information.</h4></li>
												<li><h4>We are aligned with partner companies in the fields of Document Shredding, Data Backup and Recovery and Business Continuity and Disaster Recovery in order to provide a single source to our customers.</h4></li>
												<li><h4>Our vault is a protected, climate-controlled storage environment for your highly sensitive media. It is protected by the SAPPHIRE© fire protection system – the most advanced technology today!</h4></li>
												<li><h4>Your data is transported to and from your location in a secure vehicle and storage container. We will be there when you need us. We guarantee it!</h4></li>
												<li><h4>Access to your vital information is available 24 hours per day</h4></li>
											</ul>
										</article>
							
								</div>

						</div>
						<div class="4u">
							<div class="right-sidebar">

								<!-- Sidebar -->
								<?php include('inc/right-side1 '); ?>
							
							</div>
						</div>
					</div>
				</div>
			</div>

			<!-- FOOTER FILE -->
		<?php include('inc/footer '); ?>